#!/bin/bash

### a simple script to call other executables and draw samples from the requested distributions
### Reed Essick (reed.essick@gmail.com)

#--------------------------------------------

mcvt-sample \
    "hlv-population.ini" \
    100 \
    --seed 1234 \
    --output-path "hlv-population.hdf5" \
    --Verbose \
|| exit 1

mcvt-summarize-sample \
    "hlv-population.hdf5" \
    --snr-threshold 'observed_phase_maximized_snr_net' 4.0 \
    --column mass1_source \
    --label mass1_source '$m_1^{(\mathrm{src})}$' \
    --column mass2_source \
    --label mass2_source '$m_2^{(\mathrm{src})}$' \
    --column z \
    --label z '$z$' \
    --column chi_eff \
    --label chi_eff '$\chi_\mathrm{eff}$' \
    --column right_ascension \
    --label right_ascension '$\alpha$' \
    --column declination \
    --label declination '$\delta$' \
    --column inclination \
    --label inclination '$\theta_{jn}$' \
    --column snr_net \
    --label snr_net '$\rho_\mathrm{opt}$' \
    --log snr_net \
    --column observed_phase_maximized_snr_net \
    --label observed_phase_maximized_snr_net '$\rho_\mathrm{obs}$' \
    --log observed_phase_maximized_snr_net \
    --plot-detected-distribution \
    --include-ndet \
    --tag "hlv-population" \
    --Verbose
